[package]
name = "truescad"
version = "0.5.0"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[dependencies]
dirs = "1.0"
gtk = "0.3.*"
sourceview = "0.3.*"
gdk = "0.7.*"
cairo-rs = "0.3.*"
nalgebra = "0.16"
alga = "0.7"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
num-traits = "0.2"
tessellation = "0.7"
implicit3d = "0.11"
truescad_luascad = { path = "luascad", version = "0.2" }
kiss3ddeps = { path = "kiss3ddeps" }
stl_io = "0.3"
kiss3d = "0.13"

[dev-dependencies]
bencher = "0.1.*"

[features]
gtk_3_10 = []
gtk_3_14 = ["gtk_3_10"]

# [profile.release]
# lto = true

[[bench]]
name = "render"
harness = false
