[package]
name = "truescad"
version = "0.3.4"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[dependencies]
gtk = "0.3.*"
sourceview = "0.3.*"
gdk = "0.7.*"
cairo-rs = "0.3.*"
nalgebra = "0.14"
alga = "0.5"
rayon = "0.7.*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
truescad_tessellation = { path = "tessellation", version = ">= 0.3" }
truescad_types = { path = "types", version = "0.2" }
truescad_primitive = { path = "primitive", version = "0.6" }
truescad_luascad = { path = "luascad", version = "0.2" }
stl_io = "0.3.4"
kiss3d = "0.13"

[dev-dependencies]
bencher = "0.1.*"

[features]
gtk_3_10 = []
gtk_3_14 = ["gtk_3_10"]

# [profile.release]
# lto = true

[[bench]]
name = "render"
harness = false
