[package]
name = "truescad_types"
version = "0.0.1"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[lib]
name = "truescad_types"
path = "lib.rs"

[dependencies]
nalgebra = "0.11"
lazy_static = "0.2.8"
