[package]
name = "truescad_bbox"
version = "0.6.1"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[lib]
name = "truescad_bbox"
path = "lib.rs"

[dependencies]
nalgebra = "0.14"
alga = "0.5"
num-traits = "0.2"
