[package]
name = "truescad_luascad"
version = "0.2.9"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[lib]
name = "truescad_luascad"
path = "lib.rs"

[dependencies]
hlua = "0.3"
implicit3d = "0.12"
nalgebra = "0.16"
