[package]
name = "truescad_luascad"
version = "0.2.8"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[lib]
name = "truescad_luascad"
path = "lib.rs"

[dependencies]
hlua = "0.3"
implicit3d = "0.9"
nalgebra = "0.14"
